services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:80"
    environment:
      - FILE_SERVICE_URL=http://file_service:80/api
    depends_on:
      - file_service

  file_service:
    build: ./file_storing_service
    container_name: file_service
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=postgresql://user:pass@file_db:5432/files
    depends_on:
      - file_db

  file_db:
    image: postgres:15
    container_name: file_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: files
    volumes:
      - file_db_data:/var/lib/postgresql/data

volumes:
  file_db_data:
